# Generated by Django 5.1.6 on 2025-03-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_rename_testimonial_testimonials"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Testimonials",
            new_name="Testimonial",
        ),
    ]
