# Generated by Django 5.1.6 on 2025-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0006_rename_testimonials_testimonial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Testimonial",
            new_name="Testimonials",
        ),
    ]
