# Generated by Django 5.1.6 on 2025-03-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_rename_testimonial_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="ImageModel",
        ),
    ]
