# Generated by Django 5.1.6 on 2025-03-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_bannerimage_delete_imagemodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bannerimage",
            name="name",
        ),
        migrations.AlterField(
            model_name="bannerimage",
            name="image",
            field=models.ImageField(upload_to="banners/"),
        ),
    ]
