# Generated by Django 5.1.6 on 2025-03-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_remove_bannerimage_name_alter_bannerimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_data", models.ImageField(upload_to="serviceimages/")),
            ],
        ),
    ]
