# Generated by Django 5.1.6 on 2025-03-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_serviceimages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="service_images/")),
            ],
        ),
        migrations.DeleteModel(
            name="ServiceImages",
        ),
    ]
