# Generated by Django 5.1.6 on 2025-03-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0012_service_delete_serviceimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
    ]
