# Generated by Django 5.1.6 on 2025-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0014_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestimonialFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("feedback", models.TextField()),
                ("image", models.ImageField(upload_to="testimonials/")),
                ("rating", models.IntegerField(default=5)),
            ],
        ),
    ]
