# Generated by Django 5.1.6 on 2025-03-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0015_testimonialfeedback"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TestimonialFeedback",
            new_name="TestimonialFeedback1",
        ),
    ]
