# Generated by Django 5.1.6 on 2025-03-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_rename_testimonialfeedback_testimonialfeedback1"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("article_url", models.URLField()),
            ],
        ),
    ]
