# Generated by Django 5.1.6 on 2025-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0017_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="image_url",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="blog_images/"),
        ),
    ]
