# Generated by Django 5.1.6 on 2025-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0018_remove_blogpost_image_url_blogpost_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projectdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_description", models.TextField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("location", models.CharField(default="Las Vegas, NV", max_length=255)),
            ],
        ),
    ]
