# Generated by Django 5.1.6 on 2025-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0019_projectdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="van_images/")),
                ("details", models.CharField(max_length=17)),
                ("location", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Projectdetails",
        ),
    ]
