# Generated by Django 5.1.6 on 2025-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0021_proj_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CamperVanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("image_url", models.URLField()),
                ("start_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("explore_url", models.URLField()),
                ("inventory_url", models.URLField()),
                ("is_full_inventory", models.BooleanField(default=False)),
            ],
        ),
    ]
