# Generated by Django 5.1.6 on 2025-03-31 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0022_campervanmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CamperVanModel",
        ),
    ]
