# Generated by Django 5.1.6 on 2025-03-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0024_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImagesProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(upload_to="banners/")),
            ],
        ),
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="carousel_images/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
