# Generated by Django 5.1.6 on 2025-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0025_bannerimagesproducts_carouselimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="features/")),
            ],
        ),
    ]
