# Generated by Django 5.1.6 on 2025-03-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0026_feature"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feature",
        ),
    ]
