# Generated by Django 4.2.19 on 2025-04-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
